name: Build .NET MAUI Blazor Hybrid

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: 'Muledump.NET.sln'
  PROJECT_FILE: 'Muledump.NET.csproj'
  ASSET_REPO: 'TadusPro/RotMGAssetExtractor' # update if owner/name differs
  ASSET_PATH: 'RotMGAssetExtractor'           # folder where it should live

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout main repo
      - uses: actions/checkout@v4

      # Checkout RotMGAssetExtractor from its own repo into expected folder path
      - name: Checkout asset extractor repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ASSET_REPO }}
          path: ${{ env.ASSET_PATH }}  # public repo: no token needed
          # For private repo add: token: ${{ secrets.GH_PAT }}

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          dotnet-quality: 'ga'

      - name: Install MAUI workloads
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore NuGet packages
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Build Release
        run: dotnet build ${{ env.SOLUTION_FILE }} -c Release --no-restore

      - name: Publish Windows
        run: dotnet publish ${{ env.PROJECT_FILE }} -c Release -f net8.0-windows10.0.19041.0 -p:PublishSingleFile=true -p:WindowsPackageType=msix -o publish/windows

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsOutputs
          path: publish/windows
