name: Build Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: 'Muledump.NET.sln'
  PROJECT_FILE: 'Muledump.NET.csproj'
  ASSET_REPO: 'TadusPro/RotMGAssetExtractor'
  ASSET_PATH: 'RotMGAssetExtractor'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout asset extractor repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ASSET_REPO }}
          path: ${{ env.ASSET_PATH }}

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Build (Release, Windows x64)
        run: dotnet build ${{ env.SOLUTION_FILE }} -c Release --no-restore -f net8.0-windows10.0.19041.0

      - name: Publish Windows
        run: dotnet publish ${{ env.PROJECT_FILE }} -c Release -f net8.0-windows10.0.19041.0 -r win-x64 -p:WindowsPackageType=None -p:PublishReadyToRun=false -o publish/windows

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsOutputs
          path: publish/windows
